---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Joaquín Barrutia Álvarez

jobtitle: "Pre-Doctoral Fellow, Georgetown University"
address: "Uppsala, Sweden"
fontawesome: yes
email: joaquinbarrutia@gmail.com  
github: "[quinoba](http://github.com/quinoba)"
twitter: "[j_barrutia](https://twitter.com/j_barrutia)"
#osf: "Enter 5 digit osf string here"
phone: "[+46 762617438](tel:+46762617438)"
#web: guinness.com
updated: yes

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
#linkcolor: blue
#urlcolor: no
---

\cfoot{\scriptsize  Joaquín Barrutia - CV}

# Research Interests 

- Applied Econometrics, Development Economics, Political Economy

# Education

## Uppsala University, Uppsala, Sweden
- Master of Social Sciences, Economics \hfill 2022-2024

## Instituto Tecnológico Autónomo de México (ITAM), Mexico City, Mexico 

- B.A. (Honors), Economics  \hfill 2016-2021
\begin{myitemize}
  \item[--] Thesis: "\textit{\href{https://github.com/quinoba/Spillovers_Cooperation}{We Both Step and Do Not Step in the Same Rivers: Municipal Cooperation and Water Pollution Spillovers in Mexico}}". Supervisor: Emilio Gutiérrez, Ph.D.
\end{myitemize}

- Diploma, Data Science & Machine Learning Applied to Financial Markets \hfill 2021-2022


# Experience


## Georgetown University, Washington, D.C.


- Pre-Doctoral Fellow \hfill 2023-
\begin{myitemize}
  \item[--] Working with Dr. Laurent Bouton (Georgetown) through the United Programs for Political Economy Research (UPPER Network) as part of the \href{https://upperesearch.org/grti/}{Global Research Training Initiative}.
\end{myitemize}

## Center for Economic Research ([CIE](http://cie.itam.mx/)), ITAM, Mexico City

- Reaserch Assistant \hfill 2021-
\begin{myitemize}
  \item[--] Working in a Mercury Project research team with Dr. Antonella Bandiera (ITAM), Dr. Horacio Larreguy (ITAM), and Dr. John Marshall (Columbia), partnering with fact-checkers in Kenya, South Africa, and Bolivia, conducting two studies to test approaches to counter misinformation.
\end{myitemize}
  

## UNIFIN Financiera, Mexico City

- Structured Finance Analyst \hfill 2020-2022

# Work in Progress

- "\textit{Harnessing Social Influencers to Combat Misinformation: Scalable Solutions in the Global South}"  (with Antonella Bandiera, Jeremy Bowles, Shelley Liu, Horacio Larreguy, John Marshall, and Eduardo Zago) \hfill \href{https://docsend.dropbox.com/view/a4u4tkvtzpwiuf23}{Slides}

\newpage

# Skills & Relevant Coursework

## Software

- Microsoft Office, \LaTeX, Python, QGIS, R

## Languages

- Spanish (native), English (fluent), Mandarin Chinese (HSK1)

## Relevant Coursework^[$\text{UU}=\text{Uppsala University}$, $\text{SU}=\text{Stockholm University}$]

- Microeconomic Theory (ITAM, UU), Macroeconomic Theory (ITAM, UU), Econometric Theory (ITAM, UU), Applied Microeconometrics (ITAM, UU), Time Series Econometrics (ITAM, UU), Real Analysis (ITAM, SU), Matrix Algebra (ITAM), Univariate and Multivariate Calculus (ITAM), Probability Theory (ITAM), Statistical Inference (ITAM), Bayesian Statistics (UU), Machine Learning (UU)

# Additional Training

## University of Ioannina & University of Piraeus, Spetses, Greece

- 5th Summer School in Advanced Economics (Lecturer: Jeffrey M. Woolridge, Ph.D.) \hfill 2023
\begin{myitemize}
  \item[--]Course on Causal Inference, Potential Outcomes and Difference-in-Differences estimation.
\end{myitemize}


## Causal Solutions

- Difference-in-Differences Designs (Lecturer: Pedro H. C. Sant'Anna, Ph.D.) \hfill 2023


# Academic Awards

- First Place. Undergraduate Thesis. Premio ExITAM ---Best thesis in Economics. \hfill 2023

- Honorable Mention (Top 3). Undergraduate Thesis. [Citibanamex Economics Prize](https://www.banamex.com/premioeconomia/index.html). \hfill 2021

- ITAM Special Mention Distinction. Awarded to students with an outstanding thesis
defense and a final average grade above 8.5 out of 10. \hfill 2021

- First Place. ITAM Hagamos Eco 1. Awarded for the production of audiovisual material explaining concepts for the Economics 101 course. \hfill 2021


# Scholarships & Felowships

- FIDERH (Fund for Human Resource Development). Banco de México. \hfill 2023

- Uppsala University International Scholarship Fund for an extra course. \hfill 2023

- ITAM 50 percent academic excellence scholarship for BA studies. \hfill 2016 - 2019

\newpage 

# References

\begin{minipage}[t]{0.5\textwidth}
Horacio Larreguy\\
Associate Professor\\
ITAM\\
Mexico City, Mexico\\
\faEnvelopeO \text{} \href{mailto:horacio.larreguy@itam.mx}{horacio.larreguy@itam.mx}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
Laurent Bouton\\
Professor\\
Georgetown University\\
Washington, D.C., United States\\
\faEnvelopeO \text{} \href{mailto:lb910@georgetown.edu}{lb910@georgetown.edu}
\end{minipage}
\
\begin{minipage}[t]{0.5\textwidth}
John Marshall\\
Associate Professor\\
Columbia University\\
New York, United States\\
\faEnvelopeO \text{} \href{mailto:jm4401@columbia.edu }{jm4401@columbia.edu}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
Jaakko Meriläinen\\
Assistant Professor\\
Stockholm School of Economics \\
Stockholm, Sweden\\
\faEnvelopeO \text{} \href{mailto:jaakko.merilainen@hhs.se}{ jaakko.merilainen@hhs.se}
\end{minipage}